// Grabs a random photo and sizes it according to passed in height and width parameters
export const fetchPhoto = async (width, height) => {
    const response = await fetch(`https://picsum.photos/${width}/${height}`);
    const blob = await response.blob();
    return URL.createObjectURL(blob);
}

// Gets a random username from the list of 80
export const getRandUsername = () => {
    const randomUsernamesArr = [
        'hypnopompic3',
        'epistatic65',
        'gratulatory42',
        'dakilzygoma11',
        'luminous1',
        'sigillumxx',
        'chirogymnast',
        'aardwolf123',
        'hodiernal',
        'abattoir',
        'stegophilist',
        'abattoir123',
        'hygrograph4',
        'beatlemania22',
        'reptarvadose86',
        'colloquy12',
        'abattoir44',
        'souteneur',
        'theomachy',
        'pilliwinks',
        'rhematic111',
        'leprose',
        'cupriferous',
        'acrimony7',
        'abderian',
        'aardwolf666',
        'pileusko3101',
        'lustrate',
        'obtundtday',
        'bergele_01',
        'hypocaust',
        'flageolet75',
        'mammetry42',
        'diactinal',
        'hokumtor223',
        'luminous',
        'guerdon',
        'periclitate',
        'splenial2222',
        'trimacular',
        'meilpjanky32',
        'pettifogger',
        'shihtzud',
        'headlong',
        'stupefaction',
        'lactaszoom43',
        'hushpuppy',
        'newboldwoozy',
        'enihornery',
        'idoomkaput',
        'flanker11',
        'frogman69',
        'profbloodmufti',
        'havojjitney',
        'spendthrift',
        'alfresco',
        'nomenclature',
        'behoove69',
        'oocephalus',
        'itsflippollex69',
        'mellifluous',
        'anemone',
        'vamoose5',
        'tarboosh',
        'euphonium33',
        'rookery21',
        'paltrywie_101',
        'snollygoster',
        '6pseudonym',
        'bilirubin',
        'scrivener00',
        'parabola',
        'logjamtarms242',
        '4wunderkind2',
        'tuberro2001',
        'perambulator',
        'quack4quishh',
        'discalceate',
        'pharosbormc01',
        'schlepda123cz'
    ]
    return randomUsernamesArr[Math.floor(Math.random() * 80)];
}

// Gets a random post title from the list of 60
export const getRandPostTitle = (num) => {
    const randomPostTitlesArr = [
        "Check out this pic I snapped yesterday.",
        "Ever seen something like this?",
        "No sure where I took this...",
        "Wunderlust? What does that even mean?",
        "Snapshot of the day.",
        "Advice on how to improve picture quality...",
        "I have no words.",
        "Took this with my friend Ben.",
        "Wow, what a weekend.",
        "Glad the week is over.",
        "Take a look :D",
        "I'm thinking of taking up photography",
        "This was part of a project from last November",
        "Thinking of starting a band...",
        "I stole this photo from Reddit.",
        "Anyone have advice on where to buy a good lens?",
        "Knock knock...",
        "Lost my camera near the woods of Wisconsin",
        "My cousin took this yesterday",
        "Are you even ready for this?",
        "Germany, 1872",
        "Forgot where I took this...",
        "Even my grandpa says this is a good photo",
        "Winter/Spring of 1985",
        "I took this listening to Led Zepplin",
        "Can't get enough of this",
        "Happy birthday, mom",
        "It's never a good time to stop",
        "Last Summer, after a long walk",
        "Quick snap from when I was in Italy",
        "Picture of the day: #485",
        "Might as well post this here",
        "Any chance I could be a photographer?",
        "I'm thinking of starting a portfolio, thoughts?",
        "A photo a day keeps the doctor a way",
        "Can't spell photosynthesis without 'photo'!",
        "Dear dairy... woof.",
        "Israel, 1987",
        "A still shot from the movie 'Gates of Eternity'",
        "I accidentally took this photo!",
        "Dad always said: If you love it, stick with it",
        "Last photo ever taken of this place",
        "It was surreal to experience this",
        "Anyone even on this site anymore?",
        "Opinion: Apples are better than oranges.",
        "All the way up top, looking down",
        "This is actually super zoomed in!",
        "This photo was taken by Linus Richardson, 2012",//
        "Tick tock...",
        "Time is a wasting",
        "Everything must come to an end",
        "Ever thought about just giving up on this?",
        "I know a lot of people are watching",
        "I'm always afraid to post photos here",
        "Check out this insane photo from last night's shoot",
        "Snap from photographer Anthony Bordeau",
        "Couple of sips of beer and...",
        "I don't even know where I am anymore",
        "Anyone wanna see more of this kind of stuff?",
        "Yesterday or the day before. Its all a blur",
    ]
    return randomPostTitlesArr[Math.floor(Math.random() * 60)];
}